### ISSUE TITLE
Overlap motifs might not be reported.

### ISSUE THREAD

**Issue by wososa** [RobersonLab/motif_scraper#1]
Hi @eroberson ,

Thanks for developing the tool. It is very useful. I found that motif_scraper skips reporting overlapping motifs. For example, if I look for `TCGAT` motif in this sequence:

A**TCGAT**CGATCGATCGATCGATCG

Motif_scraper will only report only the first `TCGAT`. Is this a bug?

Thanks,
Woody

**Comment by eroberson** [comment]
Hello Woody! There are two run modes depending on options you set when running. The regex package can either report overlapping or only non-overlapping matches. The argparse option "--no_motif_overlaps" should change set to skip all overlapping matches.

If running **without** setting that option is skipping overlapping motifs then I've introduced a logic error at some point. Let me take a look and I'll see if I can confirm.

**Comment by wososa** [comment]
@eroberson ,

Thanks for quick reply. Just to clarify. I didn't use "--no_motif_overlaps". I am looking forward to the solution.

Best,
Woody
